routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => requestedLocale()], function () {
    Route::get('/', function () {
        return view('home');
    })->name('home');

    Route::get('/services', function () {
        return view('services');
    })->name('services');

    Route::group(['prefix' => 'customer'], function () {
        Route::post('/log-in', 'CustomerAuth@logIn')
             ->name('customer.sign-in');
        Route::post('/log-out', 'CustomerAuth@logOut')
             ->name('customer.sign-out');
    });

    Route::get('/stages/{number}', 'StagesController@show')
         ->where(['number' => '[0-9]{1}'])
         ->name('stages.show')
         ->middleware('auth.customer');

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin'], function () {
        Route::group(['middleware' => 'auth'], function () {
            Route::get('/', function () {
                return view('admin.main');
            })->name('admin.main');

            Route::resource('purchases', 'PurchasesController');
            Route::put('/purchases/{id}/archive', 'PurchasesController@archive')
                ->name('purchases.archive');
            Route::put('/purchases/{id}/restore', 'PurchasesController@restore')
                ->name('purchases.restore');

            Route::post('/purchases/{purchase_id}/stages/{stage_number}/attachments', 'PurchasesController@attachmentsStore')
                ->name('attachments.store');
            Route::delete('/attachments/{attachment_id}', 'PurchasesController@attachmentsDestroy')
                ->name('attachments.destroy');

            Route::resource('users', 'UsersController');
        });

        Route::get('/users/{email_token}/verification', 'UsersController@verify')
             ->name('users.verification');
    });

    Auth::routes();
});

resources/views/admin/partials/_header.blade.php
<section class="top-panel">
    <ul>
        <li id="console-toggle">
            <a href="#"><i class="fa fa-bars" aria-hidden="true"></i></a>
        </li>
        <li>
            <a href="{{ route('home') }}"><i class="fa fa-home" aria-hidden="true"></i>{{ trans('content.home') }}</a>
        </li>
        <li class="exit-button">
            {!! Form::open(['route' => 'logout', 'method' => 'POST']) !!}
                {{ Form::submit(trans('forms.log-out')) }}
            {!! Form::close() !!}
        </li>
    </ul>
</section>

resources/views/admin/partials/_sidebar.blade.php
<section class="left-panel">
    <ul class="general-menu">
        <li class="@yield('purchases.status')">
            <a href="{{ route('purchases.index') }}" title="{{ trans('content.purchases') }}">
                <i class="fa fa-rocket" aria-hidden="true"></i>
                <span>{{ trans('content.purchases') }}</span>
            </a>
            <ul class="sub-menu">
                <li>
                    <a href="{{ route('purchases.index', ['type' => 'active']) }}">{{ trans('content.active') }}</a>
                    <a href="{{ route('purchases.index', ['type' => 'archived']) }}">{{ trans('content.archived') }}</a>
                    <a href="{{ route('purchases.index', ['type' => 'all']) }}">{{ trans('content.all') }}</a>
                    <a href="{{ route('purchases.create') }}">{{ trans('content.new') }}</a>
                </li>
            </ul>
        </li>
        <li class="@yield('users.status')">
            <a href="{{ route('users.index') }}" title="{{ trans('content.users') }}">
                <i class="fa fa-user" aria-hidden="true"></i>
                <span>{{ trans('content.users') }}</span>
            </a>
            <ul class="sub-menu">
                <li>
                    <a href="{{ route('users.index', ['type' => 'all']) }}">{{ trans('content.all') }}</a>
                    <a href="{{ route('users.create') }}">{{ trans('content.new') }}</a>
                </li>
            </ul>
        </li>
    </ul>
</section>